# Generated by Django 2.0.2 on 2018-05-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='file_admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, null=True)),
                ('file_download', models.CharField(max_length=255, null=True)),
                ('file_md5', models.CharField(max_length=255, null=True)),
                ('file_time', models.CharField(max_length=32)),
                ('file_dir', models.CharField(default='abc', max_length=32)),
                ('file_num', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255, verbose_name='项目名称')),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=8, verbose_name='用户名')),
                ('user_pwd', models.CharField(max_length=16, verbose_name='用户密码')),
                ('user_project', models.ManyToManyField(to='file_ftp.project')),
            ],
        ),
        migrations.AddField(
            model_name='file_admin',
            name='file_owner',
            field=models.ManyToManyField(to='file_ftp.user_info'),
        ),
        migrations.AddField(
            model_name='file_admin',
            name='file_project',
            field=models.ManyToManyField(to='file_ftp.project'),
        ),
    ]
